export const PRODUCTION_ORIGIN='https://zorbirey.github.io';
export const DEVELOPMENT_ORIGINS=Object.freeze(new Set(['http://127.0.0.1:4173','http://localhost:4173','http://127.0.0.1:8787','http://localhost:8787']));
export const SESSION_TTL_SECONDS=15*60;
export const PLAN_LEVEL=Object.freeze({free:0,premium:1,pro:2,pro_plus:3});
export const PLAN_LIMITS=Object.freeze({free:Object.freeze({practice_question:50}),premium:Object.freeze({practice_question:null}),pro:Object.freeze({practice_question:null,ai_teacher:10}),pro_plus:Object.freeze({practice_question:null,ai_teacher:25})});
const encoder=new TextEncoder(),decoder=new TextDecoder();

export function isAllowedOrigin(origin){return origin===PRODUCTION_ORIGIN||DEVELOPMENT_ORIGINS.has(origin)}
export function corsHeaders(origin){return isAllowedOrigin(origin)?{'access-control-allow-origin':origin,'access-control-allow-credentials':'false','access-control-allow-headers':'authorization, content-type, x-turnstile-token','access-control-allow-methods':'GET, POST, OPTIONS','access-control-max-age':'600','vary':'Origin'}:{'vary':'Origin'}}
export function json(body,status=200,origin=''){return new Response(JSON.stringify(body),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store, private','x-content-type-options':'nosniff','referrer-policy':'no-referrer',...corsHeaders(origin)}})}
export function unixSeconds(value=Date.now()){return Math.floor(value/1000)}
function localParts(date){const parts=new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Istanbul',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',hourCycle:'h23',timeZoneName:'longOffset'}).formatToParts(date);const get=type=>parts.find(part=>part.type===type)?.value;return {year:Number(get('year')),month:Number(get('month')),day:Number(get('day')),hour:Number(get('hour')),offset:get('timeZoneName')||'GMT+03:00'}}
function offsetMinutes(label){const match=/GMT([+-])(\d{2}):?(\d{2})/.exec(label);if(!match)throw new Error('istanbul-offset-unavailable');const minutes=Number(match[2])*60+Number(match[3]);return match[1]==='-'?-minutes:minutes}
function dateKey(year,month,day){return `${year}-${String(month).padStart(2,'0')}-${String(day).padStart(2,'0')}`}
export function quotaWindow(nowMs=Date.now()){const now=localParts(new Date(nowMs)),calendar=new Date(Date.UTC(now.year,now.month-1,now.day));if(now.hour<8)calendar.setUTCDate(calendar.getUTCDate()-1);const start={year:calendar.getUTCFullYear(),month:calendar.getUTCMonth()+1,day:calendar.getUTCDate()};const next=new Date(Date.UTC(start.year,start.month-1,start.day+1,8));const resetAt=Math.floor((next.getTime()-offsetMinutes(now.offset)*60000)/1000);return {key:dateKey(start.year,start.month,start.day),resetAt,timeZone:'Europe/Istanbul',resetHour:8}}
function base64url(bytes){return btoa(String.fromCharCode(...new Uint8Array(bytes))).replaceAll('+','-').replaceAll('/','_').replace(/=+$/,'')}
function fromBase64url(value){const normalized=value.replaceAll('-','+').replaceAll('_','/').padEnd(Math.ceil(value.length/4)*4,'=');return Uint8Array.from(atob(normalized),char=>char.charCodeAt(0))}
async function signingKey(secret){const material=await crypto.subtle.importKey('raw',encoder.encode(secret),'HKDF',false,['deriveKey']);return crypto.subtle.deriveKey({name:'HKDF',hash:'SHA-256',salt:encoder.encode('ARENA-SECURITY-CORE-V1'),info:encoder.encode('session-signing-v1')},material,{name:'HMAC',hash:'SHA-256',length:256},false,['sign','verify'])}
export async function signSession(claims,secret){const payload=base64url(encoder.encode(JSON.stringify({...claims,v:1}))),key=await signingKey(secret),signature=await crypto.subtle.sign('HMAC',key,encoder.encode(payload));return `${payload}.${base64url(signature)}`}
export async function verifySession(token,secret,now=unixSeconds()){try{const [payload,signature,...extra]=String(token||'').split('.');if(!payload||!signature||extra.length)return null;const key=await signingKey(secret),valid=await crypto.subtle.verify('HMAC',key,fromBase64url(signature),encoder.encode(payload));if(!valid)return null;const claims=JSON.parse(decoder.decode(fromBase64url(payload)));if(claims.v!==1||!claims.sid||!claims.uid||!claims.did||!Number.isInteger(claims.exp)||claims.exp<=now)return null;return claims}catch{return null}}
export async function sha256(value){const digest=await crypto.subtle.digest('SHA-256',encoder.encode(String(value)));return [...new Uint8Array(digest)].map(byte=>byte.toString(16).padStart(2,'0')).join('')}
export async function verifyTurnstile(token,env,request){if(typeof token!=='string'||token.length<10||token.length>2048||!env.TURNSTILE_SECRET_KEY)return {ok:false,reason:'turnstile_unavailable'};try{const form=new FormData();form.set('secret',env.TURNSTILE_SECRET_KEY);form.set('response',token);form.set('remoteip',request.headers.get('CF-Connecting-IP')||'');form.set('idempotency_key',crypto.randomUUID());const response=await fetch('https://challenges.cloudflare.com/turnstile/v0/siteverify',{method:'POST',body:form});if(!response.ok)return {ok:false,reason:'siteverify_http_error'};const result=await response.json();if(!result.success)return {ok:false,reason:'turnstile_rejected'};if(result.hostname!==new URL(PRODUCTION_ORIGIN).hostname)return {ok:false,reason:'turnstile_hostname'};if(result.action!=='session_bootstrap')return {ok:false,reason:'turnstile_action'};return {ok:true}}catch{return {ok:false,reason:'siteverify_unavailable'}}}
export function hasPlan(active,required){return (PLAN_LEVEL[active]??0)>=(PLAN_LEVEL[required]??Number.MAX_SAFE_INTEGER)}
