import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import test from 'node:test';
const worker=readFileSync(new URL('../src/index.ts',import.meta.url),'utf8');
const migration=readFileSync(new URL('../migrations/0003_authority_requests.sql',import.meta.url),'utf8');
const commerce=readFileSync(new URL('../src/commerce.ts',import.meta.url),'utf8');
const commerceMigration=readFileSync(new URL('../migrations/0004_commerce_verification.sql',import.meta.url),'utf8');
test('Firebase tokens are verified against project audience and issuer',()=>{assert.match(worker,/jwtVerify/);assert.match(worker,/audience:env\.FIREBASE_PROJECT_ID/);assert.match(worker,/securetoken\.google\.com/);assert.match(worker,/email_verified!==true/)});
test('existing production identity, entitlement and quota schema is reused',()=>{assert.match(worker,/INSERT INTO users/);assert.match(worker,/FROM entitlements/);assert.match(worker,/INSERT INTO daily_quotas/);assert.match(worker,/daily-question-limit/)});
test('idempotency is persisted before atomic quota mutation',()=>{assert.match(migration,/CREATE TABLE IF NOT EXISTS authority_requests/);assert.match(worker,/status='pending'/);assert.ok(worker.indexOf('INSERT INTO authority_requests')<worker.indexOf('INSERT INTO daily_quotas'))});
test('Turnstile is server validated and hostname bound',()=>{assert.match(worker,/turnstile\/v0\/siteverify/);assert.match(worker,/TURNSTILE_SECRET_KEY/);assert.match(worker,/turnstile-hostname-rejected/);assert.doesNotMatch(worker,/0x4AAAAA[A-Za-z0-9_-]{20,}/)});
test('production errors do not disclose internals',()=>{assert.match(worker,/origin-not-allowed/);assert.match(worker,/requestId/);assert.doesNotMatch(worker,/error\.stack/)});
test('Google Play subscription tokens are verified by the Publisher API and bound to the Firebase user',()=>{assert.match(commerce,/purchases\/subscriptionsv2\/tokens/);assert.match(commerce,/obfuscatedExternalAccountId/);assert.match(commerce,/purchase-token-already-claimed/);assert.match(commerce,/GOOGLE_PLAY_SERVICE_ACCOUNT_JSON/)});
test('AdMob rewards require signed SSV, configured ad unit and replay-safe transaction IDs',()=>{assert.match(commerce,/verifier-keys\.json/);assert.match(commerce,/crypto\.subtle\.verify/);assert.match(commerce,/reward-configuration-mismatch/);assert.match(commerceMigration,/transaction_id TEXT PRIMARY KEY/)});
test('provider calls are bounded by timeout, response size and reward-session expiry',()=>{assert.match(commerce,/AbortSignal\.timeout/);assert.match(commerce,/provider-response-too-large/);assert.match(commerce,/reward-callback-expired/)});
test('reward grant and quota mutation are atomic in D1',()=>{assert.match(commerceMigration,/CREATE TRIGGER IF NOT EXISTS trg_ad_reward_grant/);assert.match(commerceMigration,/RAISE\(ABORT,'daily-reward-limit'\)/);assert.match(commerceMigration,/status='verified'/)});
test('provider secrets are not committed to Wrangler config',()=>{const config=readFileSync(new URL('../wrangler.jsonc',import.meta.url),'utf8');assert.doesNotMatch(config,/private_key/);assert.doesNotMatch(config,/GOOGLE_PLAY_SERVICE_ACCOUNT_JSON/)});
